version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: medical-response-db
    restart: always
    environment:
      MYSQL_DATABASE: medical_response_db
      MYSQL_ROOT_PASSWORD: barath@2007
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./medical-response-backend
    container_name: medical-response-backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/medical_response_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: barath@2007
    ports:
      - "8080:8080"

  frontend:
    build: ./MedicalResponseApp
    container_name: medical-response-app
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql_data:
