services:
  - type: web
    name: emergency-frontend
    env: docker
    dockerfilePath: ./MedicalResponseApp/Dockerfile
    plan: free
    autoDeploy: true

  - type: web
    name: emergency-backend
    env: docker
    dockerfilePath: ./medical-response-backend/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
